export const provinces = [
  "Hà Nội",
  "TP Hồ Chí Minh",
  "Bình Dương",
  "Đà Nẵng",
  "Hải Phòng",
  "Long An",
  "Bà Rịa Vũng Tàu",
  "An Giang",
  "Bắc Giang",
  "Bắc Kạn",
  "Bạc Liêu",
  "Bắc Ninh",
  "Bến Tre",
  "Bình Định",
  "Bình Phước",
  "Bình Thuận",
  "Cà Mau",
  "Cần Thơ",
  "Cao Bằng",
  "Đắk Lắk",
  "Đắk Nông",
  "Điện Biên",
  "Đồng Nai",
  "Đồng Tháp",
  "Gia Lai",
  "Hà Giang",
  "Hà Nam",
  "Hà Tĩnh",
  "Hải Dương",
  "Hậu Giang",
  "Hòa Bình",
  "Hưng Yên",
  "Khánh Hòa",
  "Kiên Giang",
  "Kon Tum",
  "Lai Châu",
  "Lâm Đồng",
  "Lạng Sơn",
  "Lào Cai",
  "Nam Định",
  "Nghệ An",
  "Ninh Bình",
  "Ninh Thuận",
  "Phú Thọ",
  "Phú Yên",
  "Quảng Bình",
  "Quảng Nam",
  "Quảng Ngãi",
  "Quảng Ninh",
  "Quảng Trị",
  "Sóc Trăng",
  "Sơn La",
  "Tây Ninh",
  "Thái Bình",
  "Thái Nguyên",
  "Thanh Hóa",
  "Thừa Thiên Huế",
  "Tiền Giang",
  "Trà Vinh",
  "Tuyên Quang",
  "Vĩnh Long",
  "Vĩnh Phúc",
  "Yên Bái",
];

export const districts = [
  [
    {
      location_id: "65",
      level: "3",
      name: "Quận Ba Đình",
      province: "Hà Nội",
    },
    {
      location_id: "66",
      level: "3",
      name: "Huyện Ba Vì",
      province: "Hà Nội",
    },
    {
      location_id: "67",
      level: "3",
      name: "Quận Bắc Từ Liêm",
      province: "Hà Nội",
    },
    {
      location_id: "68",
      level: "3",
      name: "Quận Cầu Giấy",
      province: "Hà Nội",
    },
    {
      location_id: "69",
      level: "3",
      name: "Huyện Chương Mỹ",
      province: "Hà Nội",
    },
    {
      location_id: "70",
      level: "3",
      name: "Huyện Đan Phượng",
      province: "Hà Nội",
    },
    {
      location_id: "71",
      level: "3",
      name: "Huyện Đông Anh",
      province: "Hà Nội",
    },
    {
      location_id: "72",
      level: "3",
      name: "Quận Đống Đa",
      province: "Hà Nội",
    },
    {
      location_id: "73",
      level: "3",
      name: "Huyện Gia Lâm",
      province: "Hà Nội",
    },
    {
      location_id: "74",
      level: "3",
      name: "Quận Hà Đông",
      province: "Hà Nội",
    },
    {
      location_id: "75",
      level: "3",
      name: "Quận Hai Bà Trưng",
      province: "Hà Nội",
    },
    {
      location_id: "76",
      level: "3",
      name: "Huyện Hoài Đức",
      province: "Hà Nội",
    },
    {
      location_id: "77",
      level: "3",
      name: "Quận Hoàn Kiếm",
      province: "Hà Nội",
    },
    {
      location_id: "78",
      level: "3",
      name: "Quận Hoàng Mai",
      province: "Hà Nội",
    },
    {
      location_id: "79",
      level: "3",
      name: "Quận Long Biên",
      province: "Hà Nội",
    },
    {
      location_id: "80",
      level: "3",
      name: "Huyện Mê Linh",
      province: "Hà Nội",
    },
    {
      location_id: "81",
      level: "3",
      name: "Huyện Mỹ Đức",
      province: "Hà Nội",
    },
    {
      location_id: "82",
      level: "3",
      name: "Quận Nam Từ Liêm",
      province: "Hà Nội",
    },
    {
      location_id: "83",
      level: "3",
      name: "Huyện Phú Xuyên",
      province: "Hà Nội",
    },
    {
      location_id: "84",
      level: "3",
      name: "Huyện Phúc Thọ",
      province: "Hà Nội",
    },
    {
      location_id: "85",
      level: "3",
      name: "Huyện Quốc Oai",
      province: "Hà Nội",
    },
    {
      location_id: "86",
      level: "3",
      name: "Huyện Sóc Sơn",
      province: "Hà Nội",
    },
    {
      location_id: "87",
      level: "3",
      name: "Thị xã Sơn Tây",
      province: "Hà Nội",
    },
    {
      location_id: "88",
      level: "3",
      name: "Quận Tây Hồ",
      province: "Hà Nội",
    },
    {
      location_id: "89",
      level: "3",
      name: "Huyện Thạch Thất",
      province: "Hà Nội",
    },
    {
      location_id: "90",
      level: "3",
      name: "Huyện Thanh Oai",
      province: "Hà Nội",
    },
    {
      location_id: "91",
      level: "3",
      name: "Huyện Thanh Trì",
      province: "Hà Nội",
    },
    {
      location_id: "92",
      level: "3",
      name: "Quận Thanh Xuân",
      province: "Hà Nội",
    },
    {
      location_id: "93",
      level: "3",
      name: "Huyện Thường Tín",
      province: "Hà Nội",
    },
    {
      location_id: "94",
      level: "3",
      name: "Huyện Ứng Hòa",
      province: "Hà Nội",
    },
  ],
  [
    {
      location_id: "95",
      level: "3",
      name: "Huyện Bình Chánh",
      province: "TP Hồ Chí Minh",
    },
    {
      location_id: "96",
      level: "3",
      name: "Quận Bình Tân",
      province: "TP Hồ Chí Minh",
    },
    {
      location_id: "97",
      level: "3",
      name: "Quận Bình Thạnh",
      province: "TP Hồ Chí Minh",
    },
    {
      location_id: "98",
      level: "3",
      name: "Huyện Cần Giờ",
      province: "TP Hồ Chí Minh",
    },
    {
      location_id: "99",
      level: "3",
      name: "Huyện Củ Chi",
      province: "TP Hồ Chí Minh",
    },
    {
      location_id: "100",
      level: "3",
      name: "Quận Gò Vấp",
      province: "TP Hồ Chí Minh",
    },
    {
      location_id: "101",
      level: "3",
      name: "Huyện Hóc Môn",
      province: "TP Hồ Chí Minh",
    },
    {
      location_id: "102",
      level: "3",
      name: "Huyện Nhà Bè",
      province: "TP Hồ Chí Minh",
    },
    {
      location_id: "103",
      level: "3",
      name: "Quận Phú Nhuận",
      province: "TP Hồ Chí Minh",
    },
    {
      location_id: "104",
      level: "3",
      name: " Quận 1",
      province: "TP Hồ Chí Minh",
    },
    {
      location_id: "105",
      level: "3",
      name: " Quận 10",
      province: "TP Hồ Chí Minh",
    },
    {
      location_id: "106",
      level: "3",
      name: " Quận 11",
      province: "TP Hồ Chí Minh",
    },
    {
      location_id: "107",
      level: "3",
      name: " Quận 12",
      province: "TP Hồ Chí Minh",
    },
    {
      location_id: "108",
      level: "3",
      name: " Quận 2",
      province: "TP Hồ Chí Minh",
    },
    {
      location_id: "109",
      level: "3",
      name: " Quận 3",
      province: "TP Hồ Chí Minh",
    },
    {
      location_id: "110",
      level: "3",
      name: " Quận 4",
      province: "TP Hồ Chí Minh",
    },
    {
      location_id: "111",
      level: "3",
      name: " Quận 5",
      province: "TP Hồ Chí Minh",
    },
    {
      location_id: "112",
      level: "3",
      name: " Quận 6",
      province: "TP Hồ Chí Minh",
    },
    {
      location_id: "113",
      level: "3",
      name: " Quận 7",
      province: "TP Hồ Chí Minh",
    },
    {
      location_id: "114",
      level: "3",
      name: " Quận 8",
      province: "TP Hồ Chí Minh",
    },
    {
      location_id: "115",
      level: "3",
      name: " Quận 9",
      province: "TP Hồ Chí Minh",
    },
    {
      location_id: "116",
      level: "3",
      name: "Quận Tân Bình",
      province: "TP Hồ Chí Minh",
    },
    {
      location_id: "117",
      level: "3",
      name: "Quận Tân Phú",
      province: "TP Hồ Chí Minh",
    },
    {
      location_id: "118",
      level: "3",
      name: "Quận Thủ Đức",
      province: "TP Hồ Chí Minh",
    },
  ],
  [
    {
      location_id: "119",
      level: "3",
      name: "Huyện Bàu Bàng",
      province: "Bình Dương",
    },
    {
      location_id: "120",
      level: "3",
      name: "Huyện Bến Cát",
      province: "Bình Dương",
    },
    {
      location_id: "121",
      level: "3",
      name: "Huyện Dầu Tiếng",
      province: "Bình Dương",
    },
    {
      location_id: "122",
      level: "3",
      name: "Huyện Dĩ An",
      province: "Bình Dương",
    },
    {
      location_id: "123",
      level: "3",
      name: "Huyện Phú Giáo",
      province: "Bình Dương",
    },
    {
      location_id: "124",
      level: "3",
      name: "Huyện Tân Uyên",
      province: "Bình Dương",
    },
    {
      location_id: "125",
      level: "3",
      name: "Thị xã Thủ Dầu Một",
      province: "Bình Dương",
    },
    {
      location_id: "126",
      level: "3",
      name: "Huyện Thuận An",
      province: "Bình Dương",
    },
  ],
  [
    {
      location_id: "127",
      level: "3",
      name: "Quận Cẩm Lệ",
      province: "Đà Nẵng",
    },
    {
      location_id: "128",
      level: "3",
      name: "Quận Hải Châu",
      province: "Đà Nẵng",
    },
    {
      location_id: "129",
      level: "3",
      name: "Huyện Hòa Vang",
      province: "Đà Nẵng",
    },
    {
      location_id: "130",
      level: "3",
      name: "Huyện Hoàng Sa",
      province: "Đà Nẵng",
    },
    {
      location_id: "131",
      level: "3",
      name: "Quận Liên Chiểu",
      province: "Đà Nẵng",
    },
    {
      location_id: "132",
      level: "3",
      name: "Quận Ngũ Hành Sơn",
      province: "Đà Nẵng",
    },
    {
      location_id: "133",
      level: "3",
      name: "Quận Sơn Trà",
      province: "Đà Nẵng",
    },
    {
      location_id: "134",
      level: "3",
      name: "Quận Thanh Khê",
      province: "Đà Nẵng",
    },
  ],
  [
    {
      location_id: "135",
      level: "3",
      name: "Huyện An Dương",
      province: "Hải Phòng",
    },
    {
      location_id: "136",
      level: "3",
      name: "Huyện An Lão",
      province: "Hải Phòng",
    },
    {
      location_id: "137",
      level: "3",
      name: "Huyện Bạch Long Vĩ",
      province: "Hải Phòng",
    },
    {
      location_id: "138",
      level: "3",
      name: "Huyện Cát Hải",
      province: "Hải Phòng",
    },
    {
      location_id: "139",
      level: "3",
      name: "Quận Đồ Sơn",
      province: "Hải Phòng",
    },
    {
      location_id: "140",
      level: "3",
      name: "Quận Dương Kinh",
      province: "Hải Phòng",
    },
    {
      location_id: "141",
      level: "3",
      name: "Quận Hải An",
      province: "Hải Phòng",
    },
    {
      location_id: "142",
      level: "3",
      name: "Quận Hồng Bàng",
      province: "Hải Phòng",
    },
    {
      location_id: "143",
      level: "3",
      name: "Quận Kiến An",
      province: "Hải Phòng",
    },
    {
      location_id: "144",
      level: "3",
      name: "Huyện Kiến Thụy",
      province: "Hải Phòng",
    },
    {
      location_id: "145",
      level: "3",
      name: "Quận Lê Chân",
      province: "Hải Phòng",
    },
    {
      location_id: "146",
      level: "3",
      name: "Quận Ngô Quyền",
      province: "Hải Phòng",
    },
    {
      location_id: "147",
      level: "3",
      name: "Huyện Thủy Nguyên",
      province: "Hải Phòng",
    },
    {
      location_id: "148",
      level: "3",
      name: "Huyện Tiên Lãng",
      province: "Hải Phòng",
    },
    {
      location_id: "149",
      level: "3",
      name: "Huyện Vĩnh Bảo",
      province: "Hải Phòng",
    },
  ],
  [
    {
      location_id: "150",
      level: "3",
      name: "Huyện Bến Lức",
      province: "Long An",
    },
    {
      location_id: "151",
      level: "3",
      name: "Huyện Cần Đước",
      province: "Long An",
    },
    {
      location_id: "152",
      level: "3",
      name: "Huyện Cần Giuộc",
      province: "Long An",
    },
    {
      location_id: "153",
      level: "3",
      name: "Huyện Châu Thành",
      province: "Long An",
    },
    {
      location_id: "154",
      level: "3",
      name: "Huyện Đức Hòa",
      province: "Long An",
    },
    {
      location_id: "155",
      level: "3",
      name: "Huyện Đức Huệ",
      province: "Long An",
    },
    {
      location_id: "156",
      level: "3",
      name: "Thị xã Kiến Tường",
      province: "Long An",
    },
    {
      location_id: "157",
      level: "3",
      name: "Huyện Mộc Hóa",
      province: "Long An",
    },
    {
      location_id: "158",
      level: "3",
      name: "Thành phố Tân An",
      province: "Long An",
    },
    {
      location_id: "159",
      level: "3",
      name: "Huyện Tân Hưng",
      province: "Long An",
    },
    {
      location_id: "160",
      level: "3",
      name: "Huyện Tân Thạnh",
      province: "Long An",
    },
    {
      location_id: "161",
      level: "3",
      name: "Huyện Tân Trụ",
      province: "Long An",
    },
    {
      location_id: "162",
      level: "3",
      name: "Huyện Thạnh Hóa",
      province: "Long An",
    },
    {
      location_id: "163",
      level: "3",
      name: "Huyện Thủ Thừa",
      province: "Long An",
    },
    {
      location_id: "164",
      level: "3",
      name: "Huyện Vĩnh Hưng",
      province: "Long An",
    },
  ],
  [
    {
      location_id: "165",
      level: "3",
      name: "Thị xã Bà Rịa",
      province: "Bà Rịa Vũng Tàu",
    },
    {
      location_id: "166",
      level: "3",
      name: "Huyện Châu Đức",
      province: "Bà Rịa Vũng Tàu",
    },
    {
      location_id: "167",
      level: "3",
      name: "Huyện Côn Đảo",
      province: "Bà Rịa Vũng Tàu",
    },
    {
      location_id: "168",
      level: "3",
      name: "Huyện Đất Đỏ",
      province: "Bà Rịa Vũng Tàu",
    },
    {
      location_id: "169",
      level: "3",
      name: "Huyện Long Điền",
      province: "Bà Rịa Vũng Tàu",
    },
    {
      location_id: "170",
      level: "3",
      name: "Huyện Tân Thành",
      province: "Bà Rịa Vũng Tàu",
    },
    {
      location_id: "171",
      level: "3",
      name: "Thành phố Vũng Tàu",
      province: "Bà Rịa Vũng Tàu",
    },
    {
      location_id: "172",
      level: "3",
      name: "Huyện Xuyên Mộc",
      province: "Bà Rịa Vũng Tàu",
    },
  ],
  [
    {
      location_id: "173",
      level: "3",
      name: "Huyện An Phú",
      province: "An Giang",
    },
    {
      location_id: "174",
      level: "3",
      name: "Thị xã Châu Đốc",
      province: "An Giang",
    },
    {
      location_id: "175",
      level: "3",
      name: "Huyện Châu Phú",
      province: "An Giang",
    },
    {
      location_id: "176",
      level: "3",
      name: "Huyện Châu Thành",
      province: "An Giang",
    },
    {
      location_id: "177",
      level: "3",
      name: "Huyện Chợ Mới",
      province: "An Giang",
    },
    {
      location_id: "178",
      level: "3",
      name: "Thành phố Long Xuyên",
      province: "An Giang",
    },
    {
      location_id: "179",
      level: "3",
      name: "Huyện Phú Tân",
      province: "An Giang",
    },
    {
      location_id: "180",
      level: "3",
      name: "Thị xã Tân Châu",
      province: "An Giang",
    },
    {
      location_id: "181",
      level: "3",
      name: "Huyện Thoại Sơn",
      province: "An Giang",
    },
    {
      location_id: "182",
      level: "3",
      name: "Huyện Tịnh Biên",
      province: "An Giang",
    },
    {
      location_id: "183",
      level: "3",
      name: "Huyện Tri Tôn",
      province: "An Giang",
    },
  ],
  [
    {
      location_id: "184",
      level: "3",
      name: "Thành phố Bắc Giang",
      province: "Bắc Giang",
    },
    {
      location_id: "185",
      level: "3",
      name: "Huyện Hiệp Hòa",
      province: "Bắc Giang",
    },
    {
      location_id: "186",
      level: "3",
      name: "Huyện Lạng Giang",
      province: "Bắc Giang",
    },
    {
      location_id: "187",
      level: "3",
      name: "Huyện Lục Nam",
      province: "Bắc Giang",
    },
    {
      location_id: "188",
      level: "3",
      name: "Huyện Lục Ngạn",
      province: "Bắc Giang",
    },
    {
      location_id: "189",
      level: "3",
      name: "Huyện Sơn Động",
      province: "Bắc Giang",
    },
    {
      location_id: "190",
      level: "3",
      name: "Huyện Tân Yên",
      province: "Bắc Giang",
    },
    {
      location_id: "191",
      level: "3",
      name: "Huyện Việt Yên",
      province: "Bắc Giang",
    },
    {
      location_id: "192",
      level: "3",
      name: "Huyện Yên Dũng",
      province: "Bắc Giang",
    },
    {
      location_id: "193",
      level: "3",
      name: "Huyện Yên Thế",
      province: "Bắc Giang",
    },
  ],
  [
    {
      location_id: "194",
      level: "3",
      name: "Huyện Ba Bể",
      province: "Bắc Kạn",
    },
    {
      location_id: "195",
      level: "3",
      name: "Thị xã Bắc Kạn",
      province: "Bắc Kạn",
    },
    {
      location_id: "196",
      level: "3",
      name: "Huyện Bạch Thông",
      province: "Bắc Kạn",
    },
    {
      location_id: "197",
      level: "3",
      name: "Huyện Chợ Đồn",
      province: "Bắc Kạn",
    },
    {
      location_id: "198",
      level: "3",
      name: "Huyện Chợ Mới",
      province: "Bắc Kạn",
    },
    {
      location_id: "199",
      level: "3",
      name: "Huyện Na Rì",
      province: "Bắc Kạn",
    },
    {
      location_id: "200",
      level: "3",
      name: "Huyện Ngân Sơn",
      province: "Bắc Kạn",
    },
    {
      location_id: "201",
      level: "3",
      name: "Huyện Pác Nặm",
      province: "Bắc Kạn",
    },
  ],
  [
    {
      location_id: "202",
      level: "3",
      name: "Thành phố Bạc Liêu",
      province: "Bạc Liêu",
    },
    {
      location_id: "203",
      level: "3",
      name: "Huyện Đông Hải",
      province: "Bạc Liêu",
    },
    {
      location_id: "204",
      level: "3",
      name: "Huyện Giá Rai",
      province: "Bạc Liêu",
    },
    {
      location_id: "205",
      level: "3",
      name: "Huyện Hòa Bình",
      province: "Bạc Liêu",
    },
    {
      location_id: "206",
      level: "3",
      name: "Huyện Hồng Dân",
      province: "Bạc Liêu",
    },
    {
      location_id: "207",
      level: "3",
      name: "Huyện Phước Long",
      province: "Bạc Liêu",
    },
    {
      location_id: "208",
      level: "3",
      name: "Huyện Vĩnh Lợi",
      province: "Bạc Liêu",
    },
  ],
  [
    {
      location_id: "209",
      level: "3",
      name: "Thành phố Bắc Ninh",
      province: "Bắc Ninh",
    },
    {
      location_id: "210",
      level: "3",
      name: "Huyện Gia Bình",
      province: "Bắc Ninh",
    },
    {
      location_id: "211",
      level: "3",
      name: "Huyện Lương Tài",
      province: "Bắc Ninh",
    },
    {
      location_id: "212",
      level: "3",
      name: "Huyện Quế Võ",
      province: "Bắc Ninh",
    },
    {
      location_id: "213",
      level: "3",
      name: "Huyện Thuận Thành",
      province: "Bắc Ninh",
    },
    {
      location_id: "214",
      level: "3",
      name: "Huyện Tiên Du",
      province: "Bắc Ninh",
    },
    {
      location_id: "215",
      level: "3",
      name: "Thị xã Từ Sơn",
      province: "Bắc Ninh",
    },
    {
      location_id: "216",
      level: "3",
      name: "Huyện Yên Phong",
      province: "Bắc Ninh",
    },
  ],
  [
    {
      location_id: "217",
      level: "3",
      name: "Huyện Ba Tri",
      province: "Bến Tre",
    },
    {
      location_id: "218",
      level: "3",
      name: "Thành phố Bến Tre",
      province: "Bến Tre",
    },
    {
      location_id: "219",
      level: "3",
      name: "Huyện Bình Đại",
      province: "Bến Tre",
    },
    {
      location_id: "220",
      level: "3",
      name: "Huyện Châu Thành",
      province: "Bến Tre",
    },
    {
      location_id: "221",
      level: "3",
      name: "Huyện Chợ Lách",
      province: "Bến Tre",
    },
    {
      location_id: "222",
      level: "3",
      name: "Huyện Giồng Trôm",
      province: "Bến Tre",
    },
    {
      location_id: "223",
      level: "3",
      name: "Huyện Mỏ Cày Bắc",
      province: "Bến Tre",
    },
    {
      location_id: "224",
      level: "3",
      name: "Huyện Mỏ Cày Nam",
      province: "Bến Tre",
    },
    {
      location_id: "225",
      level: "3",
      name: "Huyện Thạnh Phú",
      province: "Bến Tre",
    },
  ],
  [
    {
      location_id: "226",
      level: "3",
      name: "Huyện An Lão",
      province: "Bình Định",
    },
    {
      location_id: "227",
      level: "3",
      name: "Huyện An Nhơn",
      province: "Bình Định",
    },
    {
      location_id: "228",
      level: "3",
      name: "Huyện Hoài Ân",
      province: "Bình Định",
    },
    {
      location_id: "229",
      level: "3",
      name: "Huyện Hoài Nhơn",
      province: "Bình Định",
    },
    {
      location_id: "230",
      level: "3",
      name: "Huyện Phù Cát",
      province: "Bình Định",
    },
    {
      location_id: "231",
      level: "3",
      name: "Huyện Phù Mỹ",
      province: "Bình Định",
    },
    {
      location_id: "232",
      level: "3",
      name: "Thành phố Quy Nhơn",
      province: "Bình Định",
    },
    {
      location_id: "233",
      level: "3",
      name: "Huyện Tây Sơn",
      province: "Bình Định",
    },
    {
      location_id: "234",
      level: "3",
      name: "Huyện Tuy Phước",
      province: "Bình Định",
    },
    {
      location_id: "235",
      level: "3",
      name: "Huyện Vân Canh",
      province: "Bình Định",
    },
    {
      location_id: "236",
      level: "3",
      name: "Huyện Vĩnh Thạnh",
      province: "Bình Định",
    },
  ],
  [
    {
      location_id: "237",
      level: "3",
      name: "Thị xã Bình Long",
      province: "Bình Phước",
    },
    {
      location_id: "238",
      level: "3",
      name: "Huyện Bù Đăng",
      province: "Bình Phước",
    },
    {
      location_id: "239",
      level: "3",
      name: "Huyện Bù Đốp",
      province: "Bình Phước",
    },
    {
      location_id: "240",
      level: "3",
      name: "Huyện Bù Gia Mập",
      province: "Bình Phước",
    },
    {
      location_id: "241",
      level: "3",
      name: "Huyện Chơn Thành",
      province: "Bình Phước",
    },
    {
      location_id: "242",
      level: "3",
      name: "Huyện Đồng Phú",
      province: "Bình Phước",
    },
    {
      location_id: "243",
      level: "3",
      name: "Thị xã Đồng Xoài",
      province: "Bình Phước",
    },
    {
      location_id: "244",
      level: "3",
      name: "Huyện Hớn Quản",
      province: "Bình Phước",
    },
    {
      location_id: "245",
      level: "3",
      name: "Huyện Lộc Ninh",
      province: "Bình Phước",
    },
    {
      location_id: "246",
      level: "3",
      name: "Thị xã Phước Long",
      province: "Bình Phước",
    },
  ],
  [
    {
      location_id: "247",
      level: "3",
      name: "Huyện Bắc Bình",
      province: "Bình Thuận",
    },
    {
      location_id: "248",
      level: "3",
      name: "Huyện Đảo Phú Quý",
      province: "Bình Thuận",
    },
    {
      location_id: "249",
      level: "3",
      name: "Huyện Đức Linh",
      province: "Bình Thuận",
    },
    {
      location_id: "250",
      level: "3",
      name: "Huyện Hàm Tân",
      province: "Bình Thuận",
    },
    {
      location_id: "251",
      level: "3",
      name: "Huyện Hàm Thuận Bắc",
      province: "Bình Thuận",
    },
    {
      location_id: "252",
      level: "3",
      name: "Huyện Hàm Thuận Nam",
      province: "Bình Thuận",
    },
    {
      location_id: "253",
      level: "3",
      name: "Thị xã La Gi",
      province: "Bình Thuận",
    },
    {
      location_id: "254",
      level: "3",
      name: "Thành phố Phan Thiết",
      province: "Bình Thuận",
    },
    {
      location_id: "255",
      level: "3",
      name: "Huyện Tánh Linh",
      province: "Bình Thuận",
    },
    {
      location_id: "256",
      level: "3",
      name: "Huyện Tuy Phong",
      province: "Bình Thuận",
    },
  ],
  [
    {
      location_id: "257",
      level: "3",
      name: "Thành phố Cà Mau",
      province: "Cà Mau",
    },
    {
      location_id: "258",
      level: "3",
      name: "Huyện Cái Nước",
      province: "Cà Mau",
    },
    {
      location_id: "259",
      level: "3",
      name: "Huyện Đầm Dơi",
      province: "Cà Mau",
    },
    {
      location_id: "260",
      level: "3",
      name: "Huyện Năm Căn",
      province: "Cà Mau",
    },
    {
      location_id: "261",
      level: "3",
      name: "Huyện Ngọc Hiển",
      province: "Cà Mau",
    },
    {
      location_id: "262",
      level: "3",
      name: "Huyện Phú Tân",
      province: "Cà Mau",
    },
    {
      location_id: "263",
      level: "3",
      name: "Huyện Thới Bình",
      province: "Cà Mau",
    },
    {
      location_id: "264",
      level: "3",
      name: "Huyện Trần Văn Thời",
      province: "Cà Mau",
    },
    {
      location_id: "265",
      level: "3",
      name: "Huyện U Minh",
      province: "Cà Mau",
    },
  ],
  [
    {
      location_id: "266",
      level: "3",
      name: "Huyện  Thới Lai",
      province: "Cần Thơ",
    },
    {
      location_id: "267",
      level: "3",
      name: "Quận Bình Thủy",
      province: "Cần Thơ",
    },
    {
      location_id: "268",
      level: "3",
      name: "Quận Cái Răng",
      province: "Cần Thơ",
    },
    {
      location_id: "269",
      level: "3",
      name: "Huyện Cờ Đỏ",
      province: "Cần Thơ",
    },
    {
      location_id: "270",
      level: "3",
      name: "Quận Ninh Kiều",
      province: "Cần Thơ",
    },
    {
      location_id: "271",
      level: "3",
      name: "Quận Ô Môn",
      province: "Cần Thơ",
    },
    {
      location_id: "272",
      level: "3",
      name: "Huyện Phong Điền",
      province: "Cần Thơ",
    },
    {
      location_id: "273",
      level: "3",
      name: "Quận Thốt Nốt",
      province: "Cần Thơ",
    },
    {
      location_id: "274",
      level: "3",
      name: "Huyện Vĩnh Thạnh",
      province: "Cần Thơ",
    },
  ],
  [
    {
      location_id: "275",
      level: "3",
      name: "Huyện Bảo Lạc",
      province: "Cao Bằng",
    },
    {
      location_id: "276",
      level: "3",
      name: "Huyện Bảo Lâm",
      province: "Cao Bằng",
    },
    {
      location_id: "277",
      level: "3",
      name: "Thị xã Cao Bằng",
      province: "Cao Bằng",
    },
    {
      location_id: "278",
      level: "3",
      name: "Huyện Hạ Lang",
      province: "Cao Bằng",
    },
    {
      location_id: "279",
      level: "3",
      name: "Huyện Hà Quảng",
      province: "Cao Bằng",
    },
    {
      location_id: "280",
      level: "3",
      name: "Huyện Hòa An",
      province: "Cao Bằng",
    },
    {
      location_id: "281",
      level: "3",
      name: "Huyện Nguyên Bình",
      province: "Cao Bằng",
    },
    {
      location_id: "282",
      level: "3",
      name: "Huyện Phục Hòa",
      province: "Cao Bằng",
    },
    {
      location_id: "283",
      level: "3",
      name: "Huyện Quảng Uyên",
      province: "Cao Bằng",
    },
    {
      location_id: "284",
      level: "3",
      name: "Huyện Thạch An",
      province: "Cao Bằng",
    },
    {
      location_id: "285",
      level: "3",
      name: "Huyện Thông Nông",
      province: "Cao Bằng",
    },
    {
      location_id: "286",
      level: "3",
      name: "Huyện Trà Lĩnh",
      province: "Cao Bằng",
    },
    {
      location_id: "287",
      level: "3",
      name: "Huyện Trùng Khánh",
      province: "Cao Bằng",
    },
  ],
  [
    {
      location_id: "288",
      level: "3",
      name: "Huyện Buôn Đôn",
      province: "Đắk Lắk",
    },
    {
      location_id: "289",
      level: "3",
      name: "Thị xã Buôn Hồ",
      province: "Đắk Lắk",
    },
    {
      location_id: "290",
      level: "3",
      name: "Thành phố Buôn Ma Thuột",
      province: "Đắk Lắk",
    },
    {
      location_id: "291",
      level: "3",
      name: "Huyện Cư Kuin",
      province: "Đắk Lắk",
    },
    {
      location_id: "292",
      level: "3",
      name: "Huyện Cư M'gar",
      province: "Đắk Lắk",
    },
    {
      location_id: "293",
      level: "3",
      name: "Huyện Ea H'Leo",
      province: "Đắk Lắk",
    },
    {
      location_id: "294",
      level: "3",
      name: "Huyện Ea Kar",
      province: "Đắk Lắk",
    },
    {
      location_id: "295",
      level: "3",
      name: "Huyện Ea Súp",
      province: "Đắk Lắk",
    },
    {
      location_id: "296",
      level: "3",
      name: "Huyện Krông Ana",
      province: "Đắk Lắk",
    },
    {
      location_id: "297",
      level: "3",
      name: "Huyện Krông Bông",
      province: "Đắk Lắk",
    },
    {
      location_id: "298",
      level: "3",
      name: "Huyện Krông Buk",
      province: "Đắk Lắk",
    },
    {
      location_id: "299",
      level: "3",
      name: "Huyện Krông Năng",
      province: "Đắk Lắk",
    },
    {
      location_id: "300",
      level: "3",
      name: "Huyện Krông Pắc",
      province: "Đắk Lắk",
    },
    {
      location_id: "301",
      level: "3",
      name: "Huyện Lăk",
      province: "Đắk Lắk",
    },
    {
      location_id: "302",
      level: "3",
      name: "Huyện M'Đrăk",
      province: "Đắk Lắk",
    },
  ],
  [
    {
      location_id: "303",
      level: "3",
      name: "Huyện Cư Jút",
      province: "Đắk Nông",
    },
    {
      location_id: "304",
      level: "3",
      name: "Huyện Dăk GLong",
      province: "Đắk Nông",
    },
    {
      location_id: "305",
      level: "3",
      name: "Huyện Dăk Mil",
      province: "Đắk Nông",
    },
    {
      location_id: "306",
      level: "3",
      name: "Huyện Dăk R'Lấp",
      province: "Đắk Nông",
    },
    {
      location_id: "307",
      level: "3",
      name: "Huyện Dăk Song",
      province: "Đắk Nông",
    },
    {
      location_id: "308",
      level: "3",
      name: "Thị xã Gia Nghĩa",
      province: "Đắk Nông",
    },
    {
      location_id: "309",
      level: "3",
      name: "Huyện Krông Nô",
      province: "Đắk Nông",
    },
    {
      location_id: "310",
      level: "3",
      name: "Huyện Tuy Đức",
      province: "Đắk Nông",
    },
  ],
  [
    {
      location_id: "311",
      level: "3",
      name: "Huyện Điện Biên",
      province: "Điện Biên",
    },
    {
      location_id: "312",
      level: "3",
      name: "Huyện Điện Biên Đông",
      province: "Điện Biên",
    },
    {
      location_id: "313",
      level: "3",
      name: "Thành phố Điện Biên Phủ",
      province: "Điện Biên",
    },
    {
      location_id: "314",
      level: "3",
      name: "Huyện Mường Ảng",
      province: "Điện Biên",
    },
    {
      location_id: "315",
      level: "3",
      name: "Huyện Mường Chà",
      province: "Điện Biên",
    },
    {
      location_id: "316",
      level: "3",
      name: "Thị xã Mường Lay",
      province: "Điện Biên",
    },
    {
      location_id: "317",
      level: "3",
      name: "Huyện Mường Nhé",
      province: "Điện Biên",
    },
    {
      location_id: "318",
      level: "3",
      name: "Huyện Nậm Pồ",
      province: "Điện Biên",
    },
    {
      location_id: "319",
      level: "3",
      name: "Huyện Tủa Chùa",
      province: "Điện Biên",
    },
    {
      location_id: "320",
      level: "3",
      name: "Huyện Tuần Giáo",
      province: "Điện Biên",
    },
  ],
  [
    {
      location_id: "321",
      level: "3",
      name: "Thành phố Biên Hòa",
      province: "Đồng Nai",
    },
    {
      location_id: "322",
      level: "3",
      name: "Huyện Cẩm Mỹ",
      province: "Đồng Nai",
    },
    {
      location_id: "323",
      level: "3",
      name: "Huyện Định Quán",
      province: "Đồng Nai",
    },
    {
      location_id: "324",
      level: "3",
      name: "Thị xã Long Khánh",
      province: "Đồng Nai",
    },
    {
      location_id: "325",
      level: "3",
      name: "Huyện Long Thành",
      province: "Đồng Nai",
    },
    {
      location_id: "326",
      level: "3",
      name: "Huyện Nhơn Trạch",
      province: "Đồng Nai",
    },
    {
      location_id: "327",
      level: "3",
      name: "Quận Tân Phú",
      province: "Đồng Nai",
    },
    {
      location_id: "328",
      level: "3",
      name: "Huyện Thống Nhất",
      province: "Đồng Nai",
    },
    {
      location_id: "329",
      level: "3",
      name: "Huyện Trảng Bom",
      province: "Đồng Nai",
    },
    {
      location_id: "330",
      level: "3",
      name: "Huyện Vĩnh Cửu",
      province: "Đồng Nai",
    },
    {
      location_id: "331",
      level: "3",
      name: "Huyện Xuân Lộc",
      province: "Đồng Nai",
    },
  ],
  [
    {
      location_id: "332",
      level: "3",
      name: "Huyện Châu Thành",
      province: "Đồng Tháp",
    },
    {
      location_id: "333",
      level: "3",
      name: "Huyện Huyện Cao Lãnh",
      province: "Đồng Tháp",
    },
    {
      location_id: "334",
      level: "3",
      name: "Huyện Huyện Hồng Ngự",
      province: "Đồng Tháp",
    },
    {
      location_id: "335",
      level: "3",
      name: "Huyện Lai Vung",
      province: "Đồng Tháp",
    },
    {
      location_id: "336",
      level: "3",
      name: "Huyện Lấp Vò",
      province: "Đồng Tháp",
    },
    {
      location_id: "337",
      level: "3",
      name: "Thị xã Sa Đéc",
      province: "Đồng Tháp",
    },
    {
      location_id: "338",
      level: "3",
      name: "Huyện Tam Nông",
      province: "Đồng Tháp",
    },
    {
      location_id: "339",
      level: "3",
      name: "Huyện Tân Hồng",
      province: "Đồng Tháp",
    },
    {
      location_id: "340",
      level: "3",
      name: "Huyện Thanh Bình",
      province: "Đồng Tháp",
    },
    {
      location_id: "341",
      level: "3",
      name: "Huyện Tháp Mười",
      province: "Đồng Tháp",
    },
    {
      location_id: "342",
      level: "3",
      name: "Thị xã Thị xã Hồng Ngự",
      province: "Đồng Tháp",
    },
    {
      location_id: "343",
      level: "3",
      name: "Thành phố Tp. Cao Lãnh",
      province: "Đồng Tháp",
    },
  ],
  [
    {
      location_id: "344",
      level: "3",
      name: "Thị xã An Khê",
      province: "Gia Lai",
    },
    {
      location_id: "345",
      level: "3",
      name: "Thị xã AYun Pa",
      province: "Gia Lai",
    },
    {
      location_id: "346",
      level: "3",
      name: "Huyện Chư Păh",
      province: "Gia Lai",
    },
    {
      location_id: "347",
      level: "3",
      name: "Huyện Chư Pưh",
      province: "Gia Lai",
    },
    {
      location_id: "348",
      level: "3",
      name: "Huyện Chư Sê",
      province: "Gia Lai",
    },
    {
      location_id: "349",
      level: "3",
      name: "Huyện ChưPRông",
      province: "Gia Lai",
    },
    {
      location_id: "350",
      level: "3",
      name: "Huyện Đăk Đoa",
      province: "Gia Lai",
    },
    {
      location_id: "351",
      level: "3",
      name: "Huyện Đăk Pơ",
      province: "Gia Lai",
    },
    {
      location_id: "352",
      level: "3",
      name: "Huyện Đức Cơ",
      province: "Gia Lai",
    },
    {
      location_id: "353",
      level: "3",
      name: "Huyện Ia Grai",
      province: "Gia Lai",
    },
    {
      location_id: "354",
      level: "3",
      name: "Huyện Ia Pa",
      province: "Gia Lai",
    },
    {
      location_id: "355",
      level: "3",
      name: "Huyện KBang",
      province: "Gia Lai",
    },
    {
      location_id: "356",
      level: "3",
      name: "Huyện Kông Chro",
      province: "Gia Lai",
    },
    {
      location_id: "357",
      level: "3",
      name: "Huyện Krông Pa",
      province: "Gia Lai",
    },
    {
      location_id: "358",
      level: "3",
      name: "Huyện Mang Yang",
      province: "Gia Lai",
    },
    {
      location_id: "359",
      level: "3",
      name: "Huyện Phú Thiện",
      province: "Gia Lai",
    },
    {
      location_id: "360",
      level: "3",
      name: "Thành phố Plei Ku",
      province: "Gia Lai",
    },
  ],
  [
    {
      location_id: "361",
      level: "3",
      name: "Huyện Bắc Mê",
      province: "Hà Giang",
    },
    {
      location_id: "362",
      level: "3",
      name: "Huyện Bắc Quang",
      province: "Hà Giang",
    },
    {
      location_id: "363",
      level: "3",
      name: "Huyện Đồng Văn",
      province: "Hà Giang",
    },
    {
      location_id: "364",
      level: "3",
      name: "Thành phố Hà Giang",
      province: "Hà Giang",
    },
    {
      location_id: "365",
      level: "3",
      name: "Huyện Hoàng Su Phì",
      province: "Hà Giang",
    },
    {
      location_id: "366",
      level: "3",
      name: "Huyện Mèo Vạc",
      province: "Hà Giang",
    },
    {
      location_id: "367",
      level: "3",
      name: "Huyện Quản Bạ",
      province: "Hà Giang",
    },
    {
      location_id: "368",
      level: "3",
      name: "Huyện Quang Bình",
      province: "Hà Giang",
    },
    {
      location_id: "369",
      level: "3",
      name: "Huyện Vị Xuyên",
      province: "Hà Giang",
    },
    {
      location_id: "370",
      level: "3",
      name: "Huyện Xín Mần",
      province: "Hà Giang",
    },
    {
      location_id: "371",
      level: "3",
      name: "Huyện Yên Minh",
      province: "Hà Giang",
    },
  ],
  [
    {
      location_id: "372",
      level: "3",
      name: "Huyện Bình Lục",
      province: "Hà Nam",
    },
    {
      location_id: "373",
      level: "3",
      name: "Huyện Duy Tiên",
      province: "Hà Nam",
    },
    {
      location_id: "374",
      level: "3",
      name: "Huyện Kim Bảng",
      province: "Hà Nam",
    },
    {
      location_id: "375",
      level: "3",
      name: "Huyện Lý Nhân",
      province: "Hà Nam",
    },
    {
      location_id: "376",
      level: "3",
      name: "Thành phố Phủ Lý",
      province: "Hà Nam",
    },
    {
      location_id: "377",
      level: "3",
      name: "Huyện Thanh Liêm",
      province: "Hà Nam",
    },
  ],
  [
    {
      location_id: "378",
      level: "3",
      name: "Huyện Cẩm Xuyên",
      province: "Hà Tĩnh",
    },
    {
      location_id: "379",
      level: "3",
      name: "Huyện Can Lộc",
      province: "Hà Tĩnh",
    },
    {
      location_id: "380",
      level: "3",
      name: "Huyện Đức Thọ",
      province: "Hà Tĩnh",
    },
    {
      location_id: "381",
      level: "3",
      name: "Thành phố Hà Tĩnh",
      province: "Hà Tĩnh",
    },
    {
      location_id: "382",
      level: "3",
      name: "Thị xã Hồng Lĩnh",
      province: "Hà Tĩnh",
    },
    {
      location_id: "383",
      level: "3",
      name: "Huyện Hương Khê",
      province: "Hà Tĩnh",
    },
    {
      location_id: "384",
      level: "3",
      name: "Huyện Hương Sơn",
      province: "Hà Tĩnh",
    },
    {
      location_id: "385",
      level: "3",
      name: "Huyện Kỳ Anh",
      province: "Hà Tĩnh",
    },
    {
      location_id: "386",
      level: "3",
      name: "Huyện Lộc Hà",
      province: "Hà Tĩnh",
    },
    {
      location_id: "387",
      level: "3",
      name: "Huyện Nghi Xuân",
      province: "Hà Tĩnh",
    },
    {
      location_id: "388",
      level: "3",
      name: "Huyện Thạch Hà",
      province: "Hà Tĩnh",
    },
    {
      location_id: "389",
      level: "3",
      name: "Huyện Vũ Quang",
      province: "Hà Tĩnh",
    },
  ],
  [
    {
      location_id: "390",
      level: "3",
      name: "Huyện Bình Giang",
      province: "Hải Dương",
    },
    {
      location_id: "391",
      level: "3",
      name: "Huyện Cẩm Giàng",
      province: "Hải Dương",
    },
    {
      location_id: "392",
      level: "3",
      name: "Thị xã Chí Linh",
      province: "Hải Dương",
    },
    {
      location_id: "393",
      level: "3",
      name: "Huyện Gia Lộc",
      province: "Hải Dương",
    },
    {
      location_id: "394",
      level: "3",
      name: "Thành phố Hải Dương",
      province: "Hải Dương",
    },
    {
      location_id: "395",
      level: "3",
      name: "Huyện Kim Thành",
      province: "Hải Dương",
    },
    {
      location_id: "396",
      level: "3",
      name: "Huyện Kinh Môn",
      province: "Hải Dương",
    },
    {
      location_id: "397",
      level: "3",
      name: "Huyện Nam Sách",
      province: "Hải Dương",
    },
    {
      location_id: "398",
      level: "3",
      name: "Huyện Ninh Giang",
      province: "Hải Dương",
    },
    {
      location_id: "399",
      level: "3",
      name: "Huyện Thanh Hà",
      province: "Hải Dương",
    },
    {
      location_id: "400",
      level: "3",
      name: "Huyện Thanh Miện",
      province: "Hải Dương",
    },
    {
      location_id: "401",
      level: "3",
      name: "Huyện Tứ Kỳ",
      province: "Hải Dương",
    },
  ],
  [
    {
      location_id: "402",
      level: "3",
      name: "Huyện Châu Thành",
      province: "Hậu Giang",
    },
    {
      location_id: "403",
      level: "3",
      name: "Huyện Châu Thành A",
      province: "Hậu Giang",
    },
    {
      location_id: "404",
      level: "3",
      name: "Huyện Long Mỹ",
      province: "Hậu Giang",
    },
    {
      location_id: "405",
      level: "3",
      name: "Thị xã Ngã Bảy",
      province: "Hậu Giang",
    },
    {
      location_id: "406",
      level: "3",
      name: "Huyện Phụng Hiệp",
      province: "Hậu Giang",
    },
    {
      location_id: "407",
      level: "3",
      name: "Thành phố Vị Thanh",
      province: "Hậu Giang",
    },
    {
      location_id: "408",
      level: "3",
      name: "Huyện Vị Thủy",
      province: "Hậu Giang",
    },
  ],
  [
    {
      location_id: "409",
      level: "3",
      name: "Huyện Cao Phong",
      province: "Hòa Bình",
    },
    {
      location_id: "410",
      level: "3",
      name: "Huyện Đà Bắc",
      province: "Hòa Bình",
    },
    {
      location_id: "411",
      level: "3",
      name: "Thành phố Hòa Bình",
      province: "Hòa Bình",
    },
    {
      location_id: "412",
      level: "3",
      name: "Huyện Kim Bôi",
      province: "Hòa Bình",
    },
    {
      location_id: "413",
      level: "3",
      name: "Huyện Kỳ Sơn",
      province: "Hòa Bình",
    },
    {
      location_id: "414",
      level: "3",
      name: "Huyện Lạc Sơn",
      province: "Hòa Bình",
    },
    {
      location_id: "415",
      level: "3",
      name: "Huyện Lạc Thủy",
      province: "Hòa Bình",
    },
    {
      location_id: "416",
      level: "3",
      name: "Huyện Lương Sơn",
      province: "Hòa Bình",
    },
    {
      location_id: "417",
      level: "3",
      name: "Huyện Mai Châu",
      province: "Hòa Bình",
    },
    {
      location_id: "418",
      level: "3",
      name: "Huyện Tân Lạc",
      province: "Hòa Bình",
    },
    {
      location_id: "419",
      level: "3",
      name: "Huyện Yên Thủy",
      province: "Hòa Bình",
    },
  ],
  [
    {
      location_id: "420",
      level: "3",
      name: "Huyện Ân Thi",
      province: "Hưng Yên",
    },
    {
      location_id: "421",
      level: "3",
      name: "Thành phố Hưng Yên",
      province: "Hưng Yên",
    },
    {
      location_id: "422",
      level: "3",
      name: "Huyện Khoái Châu",
      province: "Hưng Yên",
    },
    {
      location_id: "423",
      level: "3",
      name: "Huyện Kim Động",
      province: "Hưng Yên",
    },
    {
      location_id: "424",
      level: "3",
      name: "Huyện Mỹ Hào",
      province: "Hưng Yên",
    },
    {
      location_id: "425",
      level: "3",
      name: "Huyện Phù Cừ",
      province: "Hưng Yên",
    },
    {
      location_id: "426",
      level: "3",
      name: "Huyện Tiên Lữ",
      province: "Hưng Yên",
    },
    {
      location_id: "427",
      level: "3",
      name: "Huyện Văn Giang",
      province: "Hưng Yên",
    },
    {
      location_id: "428",
      level: "3",
      name: "Huyện Văn Lâm",
      province: "Hưng Yên",
    },
    {
      location_id: "429",
      level: "3",
      name: "Huyện Yên Mỹ",
      province: "Hưng Yên",
    },
  ],
  [
    {
      location_id: "430",
      level: "3",
      name: "Huyện Cam Lâm",
      province: "Khánh Hòa",
    },
    {
      location_id: "431",
      level: "3",
      name: "Thị xã Cam Ranh",
      province: "Khánh Hòa",
    },
    {
      location_id: "432",
      level: "3",
      name: "Huyện Diên Khánh",
      province: "Khánh Hòa",
    },
    {
      location_id: "433",
      level: "3",
      name: "Huyện Khánh Sơn",
      province: "Khánh Hòa",
    },
    {
      location_id: "434",
      level: "3",
      name: "Huyện Khánh Vĩnh",
      province: "Khánh Hòa",
    },
    {
      location_id: "435",
      level: "3",
      name: "Thành phố Nha Trang",
      province: "Khánh Hòa",
    },
    {
      location_id: "436",
      level: "3",
      name: "Thị xã Ninh Hòa",
      province: "Khánh Hòa",
    },
    {
      location_id: "437",
      level: "3",
      name: "Huyện Trường Sa",
      province: "Khánh Hòa",
    },
    {
      location_id: "438",
      level: "3",
      name: "Huyện Vạn Ninh",
      province: "Khánh Hòa",
    },
  ],
  [
    {
      location_id: "439",
      level: "3",
      name: "Huyện An Biên",
      province: "Kiên Giang",
    },
    {
      location_id: "440",
      level: "3",
      name: "Huyện An Minh",
      province: "Kiên Giang",
    },
    {
      location_id: "441",
      level: "3",
      name: "Huyện Châu Thành",
      province: "Kiên Giang",
    },
    {
      location_id: "442",
      level: "3",
      name: "Huyện Giang Thành",
      province: "Kiên Giang",
    },
    {
      location_id: "443",
      level: "3",
      name: "Huyện Giồng Riềng",
      province: "Kiên Giang",
    },
    {
      location_id: "444",
      level: "3",
      name: "Huyện Gò Quao",
      province: "Kiên Giang",
    },
    {
      location_id: "445",
      level: "3",
      name: "Thị xã Hà Tiên",
      province: "Kiên Giang",
    },
    {
      location_id: "446",
      level: "3",
      name: "Huyện Hòn Đất",
      province: "Kiên Giang",
    },
    {
      location_id: "447",
      level: "3",
      name: "Huyện Kiên Hải",
      province: "Kiên Giang",
    },
    {
      location_id: "448",
      level: "3",
      name: "Huyện Kiên Lương",
      province: "Kiên Giang",
    },
    {
      location_id: "449",
      level: "3",
      name: "Huyện Phú Quốc",
      province: "Kiên Giang",
    },
    {
      location_id: "450",
      level: "3",
      name: "Thành phố Rạch Giá",
      province: "Kiên Giang",
    },
    {
      location_id: "451",
      level: "3",
      name: "Huyện Tân Hiệp",
      province: "Kiên Giang",
    },
    {
      location_id: "452",
      level: "3",
      name: "Huyện U minh Thượng",
      province: "Kiên Giang",
    },
    {
      location_id: "453",
      level: "3",
      name: "Huyện Vĩnh Thuận",
      province: "Kiên Giang",
    },
  ],
  [
    {
      location_id: "454",
      level: "3",
      name: "Huyện Đăk Glei",
      province: "Kon Tum",
    },
    {
      location_id: "455",
      level: "3",
      name: "Huyện Đăk Hà",
      province: "Kon Tum",
    },
    {
      location_id: "456",
      level: "3",
      name: "Huyện Đăk Tô",
      province: "Kon Tum",
    },
    {
      location_id: "457",
      level: "3",
      name: "Huyện Kon Plông",
      province: "Kon Tum",
    },
    {
      location_id: "458",
      level: "3",
      name: "Huyện Kon Rẫy",
      province: "Kon Tum",
    },
    {
      location_id: "459",
      level: "3",
      name: "Thành phố KonTum",
      province: "Kon Tum",
    },
    {
      location_id: "460",
      level: "3",
      name: "Huyện Ngọc Hồi",
      province: "Kon Tum",
    },
    {
      location_id: "461",
      level: "3",
      name: "Huyện Sa Thầy",
      province: "Kon Tum",
    },
    {
      location_id: "462",
      level: "3",
      name: "Huyện Tu Mơ Rông",
      province: "Kon Tum",
    },
  ],
  [
    {
      location_id: "463",
      level: "3",
      name: "Thị xã Lai Châu",
      province: "Lai Châu",
    },
    {
      location_id: "464",
      level: "3",
      name: "Huyện Mường Tè",
      province: "Lai Châu",
    },
    {
      location_id: "465",
      level: "3",
      name: "Huyện Nậm Nhùn",
      province: "Lai Châu",
    },
    {
      location_id: "466",
      level: "3",
      name: "Huyện Phong Thổ",
      province: "Lai Châu",
    },
    {
      location_id: "467",
      level: "3",
      name: "Huyện Sìn Hồ",
      province: "Lai Châu",
    },
    {
      location_id: "468",
      level: "3",
      name: "Huyện Tam Đường",
      province: "Lai Châu",
    },
    {
      location_id: "469",
      level: "3",
      name: "Huyện Tân Uyên",
      province: "Lai Châu",
    },
    {
      location_id: "470",
      level: "3",
      name: "Huyện Than Uyên",
      province: "Lai Châu",
    },
  ],
  [
    {
      location_id: "471",
      level: "3",
      name: "Huyện Bảo Lâm",
      province: "Lâm Đồng",
    },
    {
      location_id: "472",
      level: "3",
      name: "Thành phố Bảo Lộc",
      province: "Lâm Đồng",
    },
    {
      location_id: "473",
      level: "3",
      name: "Huyện Cát Tiên",
      province: "Lâm Đồng",
    },
    {
      location_id: "474",
      level: "3",
      name: "Huyện Đạ Huoai",
      province: "Lâm Đồng",
    },
    {
      location_id: "475",
      level: "3",
      name: "Thành phố Đà Lạt",
      province: "Lâm Đồng",
    },
    {
      location_id: "476",
      level: "3",
      name: "Huyện Đạ Tẻh",
      province: "Lâm Đồng",
    },
    {
      location_id: "477",
      level: "3",
      name: "Huyện Đam Rông",
      province: "Lâm Đồng",
    },
    {
      location_id: "478",
      level: "3",
      name: "Huyện Di Linh",
      province: "Lâm Đồng",
    },
    {
      location_id: "479",
      level: "3",
      name: "Huyện Đơn Dương",
      province: "Lâm Đồng",
    },
    {
      location_id: "480",
      level: "3",
      name: "Huyện Đức Trọng",
      province: "Lâm Đồng",
    },
    {
      location_id: "481",
      level: "3",
      name: "Huyện Lạc Dương",
      province: "Lâm Đồng",
    },
    {
      location_id: "482",
      level: "3",
      name: "Huyện Lâm Hà",
      province: "Lâm Đồng",
    },
  ],
  [
    {
      location_id: "483",
      level: "3",
      name: "Huyện Bắc Sơn",
      province: "Lạng Sơn",
    },
    {
      location_id: "484",
      level: "3",
      name: "Huyện Bình Gia",
      province: "Lạng Sơn",
    },
    {
      location_id: "485",
      level: "3",
      name: "Huyện Cao Lộc",
      province: "Lạng Sơn",
    },
    {
      location_id: "486",
      level: "3",
      name: "Huyện Chi Lăng",
      province: "Lạng Sơn",
    },
    {
      location_id: "487",
      level: "3",
      name: "Huyện Đình Lập",
      province: "Lạng Sơn",
    },
    {
      location_id: "488",
      level: "3",
      name: "Huyện Hữu Lũng",
      province: "Lạng Sơn",
    },
    {
      location_id: "489",
      level: "3",
      name: "Thành phố Lạng Sơn",
      province: "Lạng Sơn",
    },
    {
      location_id: "490",
      level: "3",
      name: "Huyện Lộc Bình",
      province: "Lạng Sơn",
    },
    {
      location_id: "491",
      level: "3",
      name: "Huyện Tràng Định",
      province: "Lạng Sơn",
    },
    {
      location_id: "492",
      level: "3",
      name: "Huyện Văn Lãng",
      province: "Lạng Sơn",
    },
    {
      location_id: "493",
      level: "3",
      name: "Huyện Văn Quan",
      province: "Lạng Sơn",
    },
  ],
  [
    {
      location_id: "494",
      level: "3",
      name: "Huyện Bắc Hà",
      province: "Lào Cai",
    },
    {
      location_id: "495",
      level: "3",
      name: "Huyện Bảo Thắng",
      province: "Lào Cai",
    },
    {
      location_id: "496",
      level: "3",
      name: "Huyện Bảo Yên",
      province: "Lào Cai",
    },
    {
      location_id: "497",
      level: "3",
      name: "Huyện Bát Xát",
      province: "Lào Cai",
    },
    {
      location_id: "498",
      level: "3",
      name: "Thành phố Lào Cai",
      province: "Lào Cai",
    },
    {
      location_id: "499",
      level: "3",
      name: "Huyện Mường Khương",
      province: "Lào Cai",
    },
    {
      location_id: "500",
      level: "3",
      name: "Huyện Sa Pa",
      province: "Lào Cai",
    },
    {
      location_id: "501",
      level: "3",
      name: "Huyện Văn Bàn",
      province: "Lào Cai",
    },
    {
      location_id: "502",
      level: "3",
      name: "Huyện Xi Ma Cai",
      province: "Lào Cai",
    },
  ],
  [
    {
      location_id: "503",
      level: "3",
      name: "Huyện Giao Thủy",
      province: "Nam Định",
    },
    {
      location_id: "504",
      level: "3",
      name: "Huyện Hải Hậu",
      province: "Nam Định",
    },
    {
      location_id: "505",
      level: "3",
      name: "Huyện Mỹ Lộc",
      province: "Nam Định",
    },
    {
      location_id: "506",
      level: "3",
      name: "Thành phố Nam Định",
      province: "Nam Định",
    },
    {
      location_id: "507",
      level: "3",
      name: "Huyện Nam Trực",
      province: "Nam Định",
    },
    {
      location_id: "508",
      level: "3",
      name: "Huyện Nghĩa Hưng",
      province: "Nam Định",
    },
    {
      location_id: "509",
      level: "3",
      name: "Huyện Trực Ninh",
      province: "Nam Định",
    },
    {
      location_id: "510",
      level: "3",
      name: "Huyện Vụ Bản",
      province: "Nam Định",
    },
    {
      location_id: "511",
      level: "3",
      name: "Huyện Xuân Trường",
      province: "Nam Định",
    },
    {
      location_id: "512",
      level: "3",
      name: "Huyện Ý Yên",
      province: "Nam Định",
    },
  ],
  [
    {
      location_id: "513",
      level: "3",
      name: "Huyện Anh Sơn",
      province: "Nghệ An",
    },
    {
      location_id: "514",
      level: "3",
      name: "Huyện Con Cuông",
      province: "Nghệ An",
    },
    {
      location_id: "515",
      level: "3",
      name: "Thị xã Cửa Lò",
      province: "Nghệ An",
    },
    {
      location_id: "516",
      level: "3",
      name: "Huyện Diễn Châu",
      province: "Nghệ An",
    },
    {
      location_id: "517",
      level: "3",
      name: "Huyện Đô Lương",
      province: "Nghệ An",
    },
    {
      location_id: "518",
      level: "3",
      name: "Thị xã Hoàng Mai",
      province: "Nghệ An",
    },
    {
      location_id: "519",
      level: "3",
      name: "Huyện Hưng Nguyên",
      province: "Nghệ An",
    },
    {
      location_id: "520",
      level: "3",
      name: "Huyện Kỳ Sơn",
      province: "Nghệ An",
    },
    {
      location_id: "521",
      level: "3",
      name: "Huyện Nam Đàn",
      province: "Nghệ An",
    },
    {
      location_id: "522",
      level: "3",
      name: "Huyện Nghi Lộc",
      province: "Nghệ An",
    },
    {
      location_id: "523",
      level: "3",
      name: "Huyện Nghĩa Đàn",
      province: "Nghệ An",
    },
    {
      location_id: "524",
      level: "3",
      name: "Huyện Quế Phong",
      province: "Nghệ An",
    },
    {
      location_id: "525",
      level: "3",
      name: "Huyện Quỳ Châu",
      province: "Nghệ An",
    },
    {
      location_id: "526",
      level: "3",
      name: "Huyện Quỳ Hợp",
      province: "Nghệ An",
    },
    {
      location_id: "527",
      level: "3",
      name: "Huyện Quỳnh Lưu",
      province: "Nghệ An",
    },
    {
      location_id: "528",
      level: "3",
      name: "Huyện Tân Kỳ",
      province: "Nghệ An",
    },
    {
      location_id: "529",
      level: "3",
      name: "Thị xã Thái Hòa",
      province: "Nghệ An",
    },
    {
      location_id: "530",
      level: "3",
      name: "Huyện Thanh Chương",
      province: "Nghệ An",
    },
    {
      location_id: "531",
      level: "3",
      name: "Huyện Tương Dương",
      province: "Nghệ An",
    },
    {
      location_id: "532",
      level: "3",
      name: "Thành phố Vinh",
      province: "Nghệ An",
    },
    {
      location_id: "533",
      level: "3",
      name: "Huyện Yên Thành",
      province: "Nghệ An",
    },
  ],
  [
    {
      location_id: "534",
      level: "3",
      name: "Huyện Gia Viễn",
      province: "Ninh Bình",
    },
    {
      location_id: "535",
      level: "3",
      name: "Huyện Hoa Lư",
      province: "Ninh Bình",
    },
    {
      location_id: "536",
      level: "3",
      name: "Huyện Kim Sơn",
      province: "Ninh Bình",
    },
    {
      location_id: "537",
      level: "3",
      name: "Huyện Nho Quan",
      province: "Ninh Bình",
    },
    {
      location_id: "538",
      level: "3",
      name: "Thành phố Ninh Bình",
      province: "Ninh Bình",
    },
    {
      location_id: "539",
      level: "3",
      name: "Thị xã Tam Điệp",
      province: "Ninh Bình",
    },
    {
      location_id: "540",
      level: "3",
      name: "Huyện Yên Khánh",
      province: "Ninh Bình",
    },
    {
      location_id: "541",
      level: "3",
      name: "Huyện Yên Mô",
      province: "Ninh Bình",
    },
  ],
  [
    {
      location_id: "542",
      level: "3",
      name: "Huyện Bác Ái",
      province: "Ninh Thuận",
    },
    {
      location_id: "543",
      level: "3",
      name: "Huyện Ninh Hải",
      province: "Ninh Thuận",
    },
    {
      location_id: "544",
      level: "3",
      name: "Huyện Ninh Phước",
      province: "Ninh Thuận",
    },
    {
      location_id: "545",
      level: "3",
      name: "Huyện Ninh Sơn",
      province: "Ninh Thuận",
    },
    {
      location_id: "546",
      level: "3",
      name: "Thành phố Phan Rang - Tháp Chàm",
      province: "Ninh Thuận",
    },
    {
      location_id: "547",
      level: "3",
      name: "Huyện Thuận Bắc",
      province: "Ninh Thuận",
    },
    {
      location_id: "548",
      level: "3",
      name: "Huyện Thuận Nam",
      province: "Ninh Thuận",
    },
  ],
  [
    {
      location_id: "549",
      level: "3",
      name: "Huyện Cẩm Khê",
      province: "Phú Thọ",
    },
    {
      location_id: "550",
      level: "3",
      name: "Huyện Đoan Hùng",
      province: "Phú Thọ",
    },
    {
      location_id: "551",
      level: "3",
      name: "Huyện Hạ Hòa",
      province: "Phú Thọ",
    },
    {
      location_id: "552",
      level: "3",
      name: "Huyện Lâm Thao",
      province: "Phú Thọ",
    },
    {
      location_id: "553",
      level: "3",
      name: "Huyện Phù Ninh",
      province: "Phú Thọ",
    },
    {
      location_id: "554",
      level: "3",
      name: "Thị xã Phú Thọ",
      province: "Phú Thọ",
    },
    {
      location_id: "555",
      level: "3",
      name: "Huyện Tam Nông",
      province: "Phú Thọ",
    },
    {
      location_id: "556",
      level: "3",
      name: "Huyện Tân Sơn",
      province: "Phú Thọ",
    },
    {
      location_id: "557",
      level: "3",
      name: "Huyện Thanh Ba",
      province: "Phú Thọ",
    },
    {
      location_id: "558",
      level: "3",
      name: "Huyện Thanh Sơn",
      province: "Phú Thọ",
    },
    {
      location_id: "559",
      level: "3",
      name: "Huyện Thanh Thủy",
      province: "Phú Thọ",
    },
    {
      location_id: "560",
      level: "3",
      name: "Thành phố Việt Trì",
      province: "Phú Thọ",
    },
    {
      location_id: "561",
      level: "3",
      name: "Huyện Yên Lập",
      province: "Phú Thọ",
    },
  ],
  [
    {
      location_id: "562",
      level: "3",
      name: "Huyện Đông Hòa",
      province: "Phú Yên",
    },
    {
      location_id: "563",
      level: "3",
      name: "Huyện Đồng Xuân",
      province: "Phú Yên",
    },
    {
      location_id: "564",
      level: "3",
      name: "Huyện Phú Hòa",
      province: "Phú Yên",
    },
    {
      location_id: "565",
      level: "3",
      name: "Huyện Sơn Hòa",
      province: "Phú Yên",
    },
    {
      location_id: "566",
      level: "3",
      name: "Thị xã Sông Cầu",
      province: "Phú Yên",
    },
    {
      location_id: "567",
      level: "3",
      name: "Huyện Sông Hinh",
      province: "Phú Yên",
    },
    {
      location_id: "568",
      level: "3",
      name: "Huyện Tây Hòa",
      province: "Phú Yên",
    },
    {
      location_id: "569",
      level: "3",
      name: "Huyện Tuy An",
      province: "Phú Yên",
    },
    {
      location_id: "570",
      level: "3",
      name: "Thành phố Tuy Hòa",
      province: "Phú Yên",
    },
  ],
  [
    {
      location_id: "571",
      level: "3",
      name: "Thị xã Ba Đồn",
      province: "Quảng Bình",
    },
    {
      location_id: "572",
      level: "3",
      name: "Huyện Bố Trạch",
      province: "Quảng Bình",
    },
    {
      location_id: "573",
      level: "3",
      name: "Thành phố Đồng Hới",
      province: "Quảng Bình",
    },
    {
      location_id: "574",
      level: "3",
      name: "Huyện Lệ Thủy",
      province: "Quảng Bình",
    },
    {
      location_id: "575",
      level: "3",
      name: "Huyện Minh Hóa",
      province: "Quảng Bình",
    },
    {
      location_id: "576",
      level: "3",
      name: "Huyện Quảng Ninh",
      province: "Quảng Bình",
    },
    {
      location_id: "577",
      level: "3",
      name: "Huyện Quảng Trạch",
      province: "Quảng Bình",
    },
    {
      location_id: "578",
      level: "3",
      name: "Huyện Tuyên Hóa",
      province: "Quảng Bình",
    },
  ],
  [
    {
      location_id: "579",
      level: "3",
      name: "Huyện Bắc Trà My",
      province: "Quảng Nam",
    },
    {
      location_id: "580",
      level: "3",
      name: "Huyện Đại Lộc",
      province: "Quảng Nam",
    },
    {
      location_id: "581",
      level: "3",
      name: "Huyện Điện Bàn",
      province: "Quảng Nam",
    },
    {
      location_id: "582",
      level: "3",
      name: "Huyện Đông Giang",
      province: "Quảng Nam",
    },
    {
      location_id: "583",
      level: "3",
      name: "Huyện Duy Xuyên",
      province: "Quảng Nam",
    },
    {
      location_id: "584",
      level: "3",
      name: "Huyện Hiệp Đức",
      province: "Quảng Nam",
    },
    {
      location_id: "585",
      level: "3",
      name: "Thành phố Hội An",
      province: "Quảng Nam",
    },
    {
      location_id: "586",
      level: "3",
      name: "Huyện Nam Giang",
      province: "Quảng Nam",
    },
    {
      location_id: "587",
      level: "3",
      name: "Huyện Nam Trà My",
      province: "Quảng Nam",
    },
    {
      location_id: "588",
      level: "3",
      name: "Huyện Nông Sơn",
      province: "Quảng Nam",
    },
    {
      location_id: "589",
      level: "3",
      name: "Huyện Núi Thành",
      province: "Quảng Nam",
    },
    {
      location_id: "590",
      level: "3",
      name: "Huyện Phú Ninh",
      province: "Quảng Nam",
    },
    {
      location_id: "591",
      level: "3",
      name: "Huyện Phước Sơn",
      province: "Quảng Nam",
    },
    {
      location_id: "592",
      level: "3",
      name: "Huyện Quế Sơn",
      province: "Quảng Nam",
    },
    {
      location_id: "593",
      level: "3",
      name: "Thành phố Tam Kỳ",
      province: "Quảng Nam",
    },
    {
      location_id: "594",
      level: "3",
      name: "Huyện Tây Giang",
      province: "Quảng Nam",
    },
    {
      location_id: "595",
      level: "3",
      name: "Huyện Thăng Bình",
      province: "Quảng Nam",
    },
    {
      location_id: "596",
      level: "3",
      name: "Huyện Tiên Phước",
      province: "Quảng Nam",
    },
  ],
  [
    {
      location_id: "597",
      level: "3",
      name: "Huyện Ba Tơ",
      province: "Quảng Ngãi",
    },
    {
      location_id: "598",
      level: "3",
      name: "Huyện Bình Sơn",
      province: "Quảng Ngãi",
    },
    {
      location_id: "599",
      level: "3",
      name: "Huyện Đức Phổ",
      province: "Quảng Ngãi",
    },
    {
      location_id: "600",
      level: "3",
      name: "Huyện Lý Sơn",
      province: "Quảng Ngãi",
    },
    {
      location_id: "601",
      level: "3",
      name: "Huyện Minh Long",
      province: "Quảng Ngãi",
    },
    {
      location_id: "602",
      level: "3",
      name: "Huyện Mộ Đức",
      province: "Quảng Ngãi",
    },
    {
      location_id: "603",
      level: "3",
      name: "Huyện Nghĩa Hành",
      province: "Quảng Ngãi",
    },
    {
      location_id: "604",
      level: "3",
      name: "Thành phố Quảng Ngãi",
      province: "Quảng Ngãi",
    },
    {
      location_id: "605",
      level: "3",
      name: "Huyện Sơn Hà",
      province: "Quảng Ngãi",
    },
    {
      location_id: "606",
      level: "3",
      name: "Huyện Sơn Tây",
      province: "Quảng Ngãi",
    },
    {
      location_id: "607",
      level: "3",
      name: "Huyện Sơn Tịnh",
      province: "Quảng Ngãi",
    },
    {
      location_id: "608",
      level: "3",
      name: "Huyện Tây Trà",
      province: "Quảng Ngãi",
    },
    {
      location_id: "609",
      level: "3",
      name: "Huyện Trà Bồng",
      province: "Quảng Ngãi",
    },
    {
      location_id: "610",
      level: "3",
      name: "Huyện Tư Nghĩa",
      province: "Quảng Ngãi",
    },
  ],
  [
    {
      location_id: "611",
      level: "3",
      name: "Huyện Ba Chẽ",
      province: "Quảng Ninh",
    },
    {
      location_id: "612",
      level: "3",
      name: "Huyện Bình Liêu",
      province: "Quảng Ninh",
    },
    {
      location_id: "613",
      level: "3",
      name: "Thị xã Cẩm Phả",
      province: "Quảng Ninh",
    },
    {
      location_id: "614",
      level: "3",
      name: "Huyện Cô Tô",
      province: "Quảng Ninh",
    },
    {
      location_id: "615",
      level: "3",
      name: "Huyện Đầm Hà",
      province: "Quảng Ninh",
    },
    {
      location_id: "616",
      level: "3",
      name: "Huyện Đông Triều",
      province: "Quảng Ninh",
    },
    {
      location_id: "617",
      level: "3",
      name: "Thành phố Hạ Long",
      province: "Quảng Ninh",
    },
    {
      location_id: "618",
      level: "3",
      name: "Huyện Hải Hà",
      province: "Quảng Ninh",
    },
    {
      location_id: "619",
      level: "3",
      name: "Huyện Hoành Bồ",
      province: "Quảng Ninh",
    },
    {
      location_id: "620",
      level: "3",
      name: "Thành phố Móng Cái",
      province: "Quảng Ninh",
    },
    {
      location_id: "621",
      level: "3",
      name: "Huyện Quảng Yên",
      province: "Quảng Ninh",
    },
    {
      location_id: "622",
      level: "3",
      name: "Huyện Tiên Yên",
      province: "Quảng Ninh",
    },
    {
      location_id: "623",
      level: "3",
      name: "Thị xã Uông Bí",
      province: "Quảng Ninh",
    },
    {
      location_id: "624",
      level: "3",
      name: "Huyện Vân Đồn",
      province: "Quảng Ninh",
    },
  ],
  [
    {
      location_id: "625",
      level: "3",
      name: "Huyện Cam Lộ",
      province: "Quảng Trị",
    },
    {
      location_id: "626",
      level: "3",
      name: "Huyện Đăk Rông",
      province: "Quảng Trị",
    },
    {
      location_id: "627",
      level: "3",
      name: "Huyện Đảo Cồn cỏ",
      province: "Quảng Trị",
    },
    {
      location_id: "628",
      level: "3",
      name: "Thành phố Đông Hà",
      province: "Quảng Trị",
    },
    {
      location_id: "629",
      level: "3",
      name: "Huyện Gio Linh",
      province: "Quảng Trị",
    },
    {
      location_id: "630",
      level: "3",
      name: "Huyện Hải Lăng",
      province: "Quảng Trị",
    },
    {
      location_id: "631",
      level: "3",
      name: "Huyện Hướng Hóa",
      province: "Quảng Trị",
    },
    {
      location_id: "632",
      level: "3",
      name: "Thị xã Quảng Trị",
      province: "Quảng Trị",
    },
    {
      location_id: "633",
      level: "3",
      name: "Huyện Triệu Phong",
      province: "Quảng Trị",
    },
    {
      location_id: "634",
      level: "3",
      name: "Huyện Vĩnh Linh",
      province: "Quảng Trị",
    },
  ],
  [
    {
      location_id: "635",
      level: "3",
      name: "Huyện Châu Thành",
      province: "Sóc Trăng",
    },
    {
      location_id: "636",
      level: "3",
      name: "Huyện Cù Lao Dung",
      province: "Sóc Trăng",
    },
    {
      location_id: "637",
      level: "3",
      name: "Huyện Kế Sách",
      province: "Sóc Trăng",
    },
    {
      location_id: "638",
      level: "3",
      name: "Huyện Long Phú",
      province: "Sóc Trăng",
    },
    {
      location_id: "639",
      level: "3",
      name: "Huyện Mỹ Tú",
      province: "Sóc Trăng",
    },
    {
      location_id: "640",
      level: "3",
      name: "Huyện Mỹ Xuyên",
      province: "Sóc Trăng",
    },
    {
      location_id: "641",
      level: "3",
      name: "Huyện Ngã Năm",
      province: "Sóc Trăng",
    },
    {
      location_id: "642",
      level: "3",
      name: "Thành phố Sóc Trăng",
      province: "Sóc Trăng",
    },
    {
      location_id: "643",
      level: "3",
      name: "Huyện Thạnh Trị",
      province: "Sóc Trăng",
    },
    {
      location_id: "644",
      level: "3",
      name: "Huyện Trần Đề",
      province: "Sóc Trăng",
    },
    {
      location_id: "645",
      level: "3",
      name: "Huyện Vĩnh Châu",
      province: "Sóc Trăng",
    },
  ],
  [
    {
      location_id: "646",
      level: "3",
      name: "Huyện Bắc Yên",
      province: "Sơn La",
    },
    {
      location_id: "647",
      level: "3",
      name: "Huyện Mai Sơn",
      province: "Sơn La",
    },
    {
      location_id: "648",
      level: "3",
      name: "Huyện Mộc Châu",
      province: "Sơn La",
    },
    {
      location_id: "649",
      level: "3",
      name: "Huyện Mường La",
      province: "Sơn La",
    },
    {
      location_id: "650",
      level: "3",
      name: "Huyện Phù Yên",
      province: "Sơn La",
    },
    {
      location_id: "651",
      level: "3",
      name: "Huyện Quỳnh Nhai",
      province: "Sơn La",
    },
    {
      location_id: "652",
      level: "3",
      name: "Thành phố Sơn La",
      province: "Sơn La",
    },
    {
      location_id: "653",
      level: "3",
      name: "Huyện Sông Mã",
      province: "Sơn La",
    },
    {
      location_id: "654",
      level: "3",
      name: "Huyện Sốp Cộp",
      province: "Sơn La",
    },
    {
      location_id: "655",
      level: "3",
      name: "Huyện Thuận Châu",
      province: "Sơn La",
    },
    {
      location_id: "656",
      level: "3",
      name: "Huyện Vân Hồ",
      province: "Sơn La",
    },
    {
      location_id: "657",
      level: "3",
      name: "Huyện Yên Châu",
      province: "Sơn La",
    },
  ],
  [
    {
      location_id: "658",
      level: "3",
      name: "Huyện Bến Cầu",
      province: "Tây Ninh",
    },
    {
      location_id: "659",
      level: "3",
      name: "Huyện Châu Thành",
      province: "Tây Ninh",
    },
    {
      location_id: "660",
      level: "3",
      name: "Huyện Dương Minh Châu",
      province: "Tây Ninh",
    },
    {
      location_id: "661",
      level: "3",
      name: "Huyện Gò Dầu",
      province: "Tây Ninh",
    },
    {
      location_id: "662",
      level: "3",
      name: "Huyện Hòa Thành",
      province: "Tây Ninh",
    },
    {
      location_id: "663",
      level: "3",
      name: "Huyện Tân Biên",
      province: "Tây Ninh",
    },
    {
      location_id: "664",
      level: "3",
      name: "Huyện Tân Châu",
      province: "Tây Ninh",
    },
    {
      location_id: "665",
      level: "3",
      name: "Thị xã Tây Ninh",
      province: "Tây Ninh",
    },
    {
      location_id: "666",
      level: "3",
      name: "Huyện Trảng Bàng",
      province: "Tây Ninh",
    },
  ],
  [
    {
      location_id: "667",
      level: "3",
      name: "Huyện Đông Hưng",
      province: "Thái Bình",
    },
    {
      location_id: "668",
      level: "3",
      name: "Huyện Hưng Hà",
      province: "Thái Bình",
    },
    {
      location_id: "669",
      level: "3",
      name: "Huyện Kiến Xương",
      province: "Thái Bình",
    },
    {
      location_id: "670",
      level: "3",
      name: "Huyện Quỳnh Phụ",
      province: "Thái Bình",
    },
    {
      location_id: "671",
      level: "3",
      name: "Thành phố Thái Bình",
      province: "Thái Bình",
    },
    {
      location_id: "672",
      level: "3",
      name: "Huyện Thái Thuỵ",
      province: "Thái Bình",
    },
    {
      location_id: "673",
      level: "3",
      name: "Huyện Tiền Hải",
      province: "Thái Bình",
    },
    {
      location_id: "674",
      level: "3",
      name: "Huyện Vũ Thư",
      province: "Thái Bình",
    },
  ],
  [
    {
      location_id: "675",
      level: "3",
      name: "Huyện Đại Từ",
      province: "Thái Nguyên",
    },
    {
      location_id: "676",
      level: "3",
      name: "Huyện Định Hóa",
      province: "Thái Nguyên",
    },
    {
      location_id: "677",
      level: "3",
      name: "Huyện Đồng Hỷ",
      province: "Thái Nguyên",
    },
    {
      location_id: "678",
      level: "3",
      name: "Huyện Phổ Yên",
      province: "Thái Nguyên",
    },
    {
      location_id: "679",
      level: "3",
      name: "Huyện Phú Bình",
      province: "Thái Nguyên",
    },
    {
      location_id: "680",
      level: "3",
      name: "Huyện Phú Lương",
      province: "Thái Nguyên",
    },
    {
      location_id: "681",
      level: "3",
      name: "Thị xã Sông Công",
      province: "Thái Nguyên",
    },
    {
      location_id: "682",
      level: "3",
      name: "Thành phố Thái Nguyên",
      province: "Thái Nguyên",
    },
    {
      location_id: "683",
      level: "3",
      name: "Huyện Võ Nhai",
      province: "Thái Nguyên",
    },
  ],
  [
    {
      location_id: "684",
      level: "3",
      name: "Huyện Bá Thước",
      province: "Thanh Hóa",
    },
    {
      location_id: "685",
      level: "3",
      name: "Thị xã Bỉm Sơn",
      province: "Thanh Hóa",
    },
    {
      location_id: "686",
      level: "3",
      name: "Huyện Cẩm Thủy",
      province: "Thanh Hóa",
    },
    {
      location_id: "687",
      level: "3",
      name: "Huyện Đông Sơn",
      province: "Thanh Hóa",
    },
    {
      location_id: "688",
      level: "3",
      name: "Huyện Hà Trung",
      province: "Thanh Hóa",
    },
    {
      location_id: "689",
      level: "3",
      name: "Huyện Hậu Lộc",
      province: "Thanh Hóa",
    },
    {
      location_id: "690",
      level: "3",
      name: "Huyện Hoằng Hóa",
      province: "Thanh Hóa",
    },
    {
      location_id: "691",
      level: "3",
      name: "Huyện Lang Chánh",
      province: "Thanh Hóa",
    },
    {
      location_id: "692",
      level: "3",
      name: "Huyện Mường Lát",
      province: "Thanh Hóa",
    },
    {
      location_id: "693",
      level: "3",
      name: "Huyện Nga Sơn",
      province: "Thanh Hóa",
    },
    {
      location_id: "694",
      level: "3",
      name: "Huyện Ngọc Lặc",
      province: "Thanh Hóa",
    },
    {
      location_id: "695",
      level: "3",
      name: "Huyện Như Thanh",
      province: "Thanh Hóa",
    },
    {
      location_id: "696",
      level: "3",
      name: "Huyện Như Xuân",
      province: "Thanh Hóa",
    },
    {
      location_id: "697",
      level: "3",
      name: "Huyện Nông Cống",
      province: "Thanh Hóa",
    },
    {
      location_id: "698",
      level: "3",
      name: "Huyện Quan Hóa",
      province: "Thanh Hóa",
    },
    {
      location_id: "699",
      level: "3",
      name: "Huyện Quan Sơn",
      province: "Thanh Hóa",
    },
    {
      location_id: "700",
      level: "3",
      name: "Huyện Quảng Xương",
      province: "Thanh Hóa",
    },
    {
      location_id: "701",
      level: "3",
      name: "Thị xã Sầm Sơn",
      province: "Thanh Hóa",
    },
    {
      location_id: "702",
      level: "3",
      name: "Huyện Thạch Thành",
      province: "Thanh Hóa",
    },
    {
      location_id: "703",
      level: "3",
      name: "Thành phố Thanh Hóa",
      province: "Thanh Hóa",
    },
    {
      location_id: "704",
      level: "3",
      name: "Huyện Thiệu Hóa",
      province: "Thanh Hóa",
    },
    {
      location_id: "705",
      level: "3",
      name: "Huyện Thọ Xuân",
      province: "Thanh Hóa",
    },
    {
      location_id: "706",
      level: "3",
      name: "Huyện Thường Xuân",
      province: "Thanh Hóa",
    },
    {
      location_id: "707",
      level: "3",
      name: "Huyện Tĩnh Gia",
      province: "Thanh Hóa",
    },
    {
      location_id: "708",
      level: "3",
      name: "Huyện Triệu Sơn",
      province: "Thanh Hóa",
    },
    {
      location_id: "709",
      level: "3",
      name: "Huyện Vĩnh Lộc",
      province: "Thanh Hóa",
    },
    {
      location_id: "710",
      level: "3",
      name: "Huyện Yên Định",
      province: "Thanh Hóa",
    },
  ],
  [
    {
      location_id: "711",
      level: "3",
      name: "Huyện A Lưới",
      province: "Thừa Thiên Huế",
    },
    {
      location_id: "712",
      level: "3",
      name: "Thành phố Huế",
      province: "Thừa Thiên Huế",
    },
    {
      location_id: "713",
      level: "3",
      name: "Thị xã Hương Thủy",
      province: "Thừa Thiên Huế",
    },
    {
      location_id: "714",
      level: "3",
      name: "Huyện Hương Trà",
      province: "Thừa Thiên Huế",
    },
    {
      location_id: "715",
      level: "3",
      name: "Huyện Nam Đông",
      province: "Thừa Thiên Huế",
    },
    {
      location_id: "716",
      level: "3",
      name: "Huyện Phong Điền",
      province: "Thừa Thiên Huế",
    },
    {
      location_id: "717",
      level: "3",
      name: "Huyện Phú Lộc",
      province: "Thừa Thiên Huế",
    },
    {
      location_id: "718",
      level: "3",
      name: "Huyện Phú Vang",
      province: "Thừa Thiên Huế",
    },
    {
      location_id: "719",
      level: "3",
      name: "Huyện Quảng Điền",
      province: "Thừa Thiên Huế",
    },
  ],
  [
    {
      location_id: "720",
      level: "3",
      name: "Huyện Cái Bè",
      province: "Tiền Giang",
    },
    {
      location_id: "721",
      level: "3",
      name: "Huyện Châu Thành",
      province: "Tiền Giang",
    },
    {
      location_id: "722",
      level: "3",
      name: "Huyện Chợ Gạo",
      province: "Tiền Giang",
    },
    {
      location_id: "723",
      level: "3",
      name: "Thị xã Gò Công",
      province: "Tiền Giang",
    },
    {
      location_id: "724",
      level: "3",
      name: "Huyện Gò Công Đông",
      province: "Tiền Giang",
    },
    {
      location_id: "725",
      level: "3",
      name: "Huyện Gò Công Tây",
      province: "Tiền Giang",
    },
    {
      location_id: "726",
      level: "3",
      name: "Huyện Huyện Cai Lậy",
      province: "Tiền Giang",
    },
    {
      location_id: "727",
      level: "3",
      name: "Thành phố Mỹ Tho",
      province: "Tiền Giang",
    },
    {
      location_id: "728",
      level: "3",
      name: "Huyện Tân Phú Đông",
      province: "Tiền Giang",
    },
    {
      location_id: "729",
      level: "3",
      name: "Huyện Tân Phước",
      province: "Tiền Giang",
    },
    {
      location_id: "730",
      level: "3",
      name: "Thị xã Thị Xã Cai Lậy",
      province: "Tiền Giang",
    },
  ],
  [
    {
      location_id: "731",
      level: "3",
      name: "Huyện Càng Long",
      province: "Trà Vinh",
    },
    {
      location_id: "732",
      level: "3",
      name: "Huyện Cầu Kè",
      province: "Trà Vinh",
    },
    {
      location_id: "733",
      level: "3",
      name: "Huyện Cầu Ngang",
      province: "Trà Vinh",
    },
    {
      location_id: "734",
      level: "3",
      name: "Huyện Châu Thành",
      province: "Trà Vinh",
    },
    {
      location_id: "735",
      level: "3",
      name: "Huyện Duyên Hải",
      province: "Trà Vinh",
    },
    {
      location_id: "736",
      level: "3",
      name: "Huyện Tiểu Cần",
      province: "Trà Vinh",
    },
    {
      location_id: "737",
      level: "3",
      name: "Huyện Trà Cú",
      province: "Trà Vinh",
    },
    {
      location_id: "738",
      level: "3",
      name: "Thành phố Trà Vinh",
      province: "Trà Vinh",
    },
  ],
  [
    {
      location_id: "739",
      level: "3",
      name: "Huyện Chiêm Hóa",
      province: "Tuyên Quang",
    },
    {
      location_id: "740",
      level: "3",
      name: "Huyện Hàm Yên",
      province: "Tuyên Quang",
    },
    {
      location_id: "741",
      level: "3",
      name: "Huyện Lâm Bình",
      province: "Tuyên Quang",
    },
    {
      location_id: "742",
      level: "3",
      name: "Huyện Na Hang",
      province: "Tuyên Quang",
    },
    {
      location_id: "743",
      level: "3",
      name: "Huyện Sơn Dương",
      province: "Tuyên Quang",
    },
    {
      location_id: "744",
      level: "3",
      name: "Thành phố Tuyên Quang",
      province: "Tuyên Quang",
    },
    {
      location_id: "745",
      level: "3",
      name: "Huyện Yên Sơn",
      province: "Tuyên Quang",
    },
  ],
  [
    {
      location_id: "746",
      level: "3",
      name: "Huyện Bình Minh",
      province: "Vĩnh Long",
    },
    {
      location_id: "747",
      level: "3",
      name: "Quận Bình Tân",
      province: "Vĩnh Long",
    },
    {
      location_id: "748",
      level: "3",
      name: "Huyện Long Hồ",
      province: "Vĩnh Long",
    },
    {
      location_id: "749",
      level: "3",
      name: "Huyện Mang Thít",
      province: "Vĩnh Long",
    },
    {
      location_id: "750",
      level: "3",
      name: "Huyện Tam Bình",
      province: "Vĩnh Long",
    },
    {
      location_id: "751",
      level: "3",
      name: "Huyện Trà Ôn",
      province: "Vĩnh Long",
    },
    {
      location_id: "752",
      level: "3",
      name: "Thành phố Vĩnh Long",
      province: "Vĩnh Long",
    },
    {
      location_id: "753",
      level: "3",
      name: "Huyện Vũng Liêm",
      province: "Vĩnh Long",
    },
  ],
  [
    {
      location_id: "754",
      level: "3",
      name: "Huyện Bình Xuyên",
      province: "Vĩnh Phúc",
    },
    {
      location_id: "755",
      level: "3",
      name: "Huyện Lập Thạch",
      province: "Vĩnh Phúc",
    },
    {
      location_id: "756",
      level: "3",
      name: "Thị xã Phúc Yên",
      province: "Vĩnh Phúc",
    },
    {
      location_id: "757",
      level: "3",
      name: "Huyện Sông Lô",
      province: "Vĩnh Phúc",
    },
    {
      location_id: "758",
      level: "3",
      name: "Huyện Tam Đảo",
      province: "Vĩnh Phúc",
    },
    {
      location_id: "759",
      level: "3",
      name: "Huyện Tam Dương",
      province: "Vĩnh Phúc",
    },
    {
      location_id: "760",
      level: "3",
      name: "Huyện Vĩnh Tường",
      province: "Vĩnh Phúc",
    },
    {
      location_id: "761",
      level: "3",
      name: "Thành phố Vĩnh Yên",
      province: "Vĩnh Phúc",
    },
    {
      location_id: "762",
      level: "3",
      name: "Huyện Yên Lạc",
      province: "Vĩnh Phúc",
    },
  ],
  [
    {
      location_id: "763",
      level: "3",
      name: "Huyện Lục Yên",
      province: "Yên Bái",
    },
    {
      location_id: "764",
      level: "3",
      name: "Huyện Mù Cang Chải",
      province: "Yên Bái",
    },
    {
      location_id: "765",
      level: "3",
      name: "Thị xã Nghĩa Lộ",
      province: "Yên Bái",
    },
    {
      location_id: "766",
      level: "3",
      name: "Huyện Trạm Tấu",
      province: "Yên Bái",
    },
    {
      location_id: "767",
      level: "3",
      name: "Huyện Trấn Yên",
      province: "Yên Bái",
    },
    {
      location_id: "768",
      level: "3",
      name: "Huyện Văn Chấn",
      province: "Yên Bái",
    },
    {
      location_id: "769",
      level: "3",
      name: "Huyện Văn Yên",
      province: "Yên Bái",
    },
    {
      location_id: "770",
      level: "3",
      name: "Thành phố Yên Bái",
      province: "Yên Bái",
    },
    {
      location_id: "771",
      level: "3",
      name: "Huyện Yên Bình",
      province: "Yên Bái",
    },
  ],
];
